//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateStatuses
    {
        public int CandidateId { get; set; }
        public int StatusId { get; set; }
        public bool Wanted { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Candidates Candidates { get; set; }
    }
}
