//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class The_MatchmakerEntities : DbContext
    {
        public The_MatchmakerEntities()
            : base("name=The_MatchmakerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CandidateStatuses> CandidateStatuses { get; set; }
        public virtual DbSet<CandidateWantedComunities> CandidateWantedComunities { get; set; }
        public virtual DbSet<community> community { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<ListOfMosdot> ListOfMosdot { get; set; }
        public virtual DbSet<ManCandidate> ManCandidate { get; set; }
        public virtual DbSet<MosdotToCandidate> MosdotToCandidate { get; set; }
        public virtual DbSet<OccupationTypes> OccupationTypes { get; set; }
        public virtual DbSet<Shadchnit> Shadchnit { get; set; }
        public virtual DbSet<Siblings> Siblings { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<TypesOfSteps> TypesOfSteps { get; set; }
        public virtual DbSet<WhatImLookingFor> WhatImLookingFor { get; set; }
        public virtual DbSet<WomenCandidate> WomenCandidate { get; set; }
        public virtual DbSet<StepsOfProposal> StepsOfProposal { get; set; }
        public virtual DbSet<ProposalInProcess> ProposalInProcess { get; set; }
        public virtual DbSet<Candidates> Candidates { get; set; }
    }
}
