//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class MosdotToCandidate
    {
        public int codeMC { get; set; }
        public Nullable<int> codeMosad { get; set; }
        public int codeCandidate { get; set; }
        public Nullable<System.DateTime> yearOfFinish { get; set; }
    
        public virtual Candidates Candidates { get; set; }
        public virtual ListOfMosdot ListOfMosdot { get; set; }
    }
}
