//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalInProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProposalInProcess()
        {
            this.StepsOfProposal = new HashSet<StepsOfProposal>();
        }
    
        public int codeP { get; set; }
        public int codeBT { get; set; }
        public int codeBN { get; set; }
        public Nullable<int> stepMeeting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StepsOfProposal> StepsOfProposal { get; set; }
        public virtual Candidates Candidates { get; set; }
        public virtual Candidates Candidates1 { get; set; }
    }
}
