//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siblings
    {
        public int siblingId { get; set; }
        public int candidateId { get; set; }
        public string name { get; set; }
        public System.DateTime datebir { get; set; }
        public Nullable<bool> isMarried { get; set; }
        public string description { get; set; }
    
        public virtual Candidates Candidates { get; set; }
    }
}
